<?php
    die('exit');
    
    set_time_limit(0);

	include('functions.php');

    $target_date = '2021-09-02';

    $result_picksheets = $mysqli->prepare("SELECT `pickerSheets`.`id`, `pickerSheets`.`customer_id`, SUM(`invoice_payments`.`amount`) as `paid` FROM `pickerSheets` left join `invoice_payments` on `invoice_payments`.`payment_method` != 'CREDIT_NOTE' && `pickerSheets`.`id` = `invoice_payments`.`invoice_id` WHERE `pickerSheets`.`completed` = 1 && `pickerSheets`.`date_completed` <= ? GROUP by `pickerSheets`.`id`");
    $result_picksheets->bind_param('s',$target_date);
    $result_picksheets->execute();
    $result_picksheets = $result_picksheets->get_result();
    $i=0;
    while($picksheet = $result_picksheets->fetch_assoc()){
        $i++;
        
        $this_price = (float) invoiceTotal($picksheet['id']);

        if(($this_price - $picksheet['paid']) <= $epsilon){ continue; }
        
        
        $epsilon = 0.00001;
        $total_credit = totalValueCreditedOnInvoiceID($picksheet['id']);
        $currentOutstanding = (float) $this_price - $picksheet['paid'] - $total_credit;

        $invoice_id = $picksheet['id'];

        $paymentQuery = $mysqli->prepare("INSERT into invoice_payments (invoice_id, payment_method, amount, meta_data, payment_recorded_by) VALUES (?, 'CHEQUE', ? , 'payment generated by system', 2)");
        $paymentQuery->bind_param('id',$invoice_id,$currentOutstanding);
        $paymentQuery->execute();
    }

    echo 'done';
?>