<?php
    die('exit');
    
    set_time_limit(0);

	include('functions.php');

    $target_date = '2021-09-02';

    $result_picksheets = mysqli_query($conn, "SELECT pickerSheets.id, pickerSheets.customer_id, SUM(invoice_payments.amount) as paid FROM `pickerSheets` left join invoice_payments on invoice_payments.payment_method != 'CREDIT_NOTE' && pickerSheets.id = invoice_payments.invoice_id WHERE pickerSheets.completed = 1 && pickerSheets.date_completed <= '$target_date' GROUP by pickerSheets.id");
    $i=0;
    while($picksheet = mysqli_fetch_array($result_picksheets)){
        $i++;
        
        $this_price = (float) invoiceTotal($picksheet['id']);

        if(($this_price - $picksheet['paid']) <= $epsilon){ continue; }
        
        
        $epsilon = 0.00001;
        $total_credit = totalValueCreditedOnInvoiceID($picksheet['id']);
        $currentOutstanding = (float) $this_price - $picksheet['paid'] - $total_credit;

        $invoice_id = $picksheet['id'];

        $paymentQuery = "INSERT into invoice_payments (invoice_id, payment_method, amount, meta_data, payment_recorded_by) VALUES ('$invoice_id', 'CHEQUE', $currentOutstanding, 'payment generated by system', 2)";
        mysqli_query($conn, $paymentQuery);
    }

    echo 'done';
?>